
# Enable ISO 8601 formatting as standard.
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

# DB base connection
spring.datasource:
  url: jdbc:mysql://localhost/account-db
  username: user
  password: pwd

spring:
  jpa:
    hibernate:
      ddl-auto: update
---
spring.config.activate.on-profile: docker

# DB connection to Docker
spring.datasource.url: jdbc:mysql://mysql/account-db